complete -c acai -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c acai -n "__fish_use_subcommand" -f -a "install" -d 'Installs packages'
complete -c acai -n "__fish_use_subcommand" -f -a "search" -d 'Searches seeds'
complete -c acai -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c acai -n "__fish_seen_subcommand_from install" -s h -l help -d 'Print help'
complete -c acai -n "__fish_seen_subcommand_from search" -s h -l help -d 'Print help'
complete -c acai -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from search; and not __fish_seen_subcommand_from help" -f -a "install" -d 'Installs packages'
complete -c acai -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from search; and not __fish_seen_subcommand_from help" -f -a "search" -d 'Searches seeds'
complete -c acai -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from search; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
